server:
  port: 8084

spring:
  application:
    name: primebiz-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/primebiz_user
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
