server:
  port: 8087

spring:
  application:
    name: primebiz-shipping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/primebiz_shipping
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888

spring:
  cloud:
    stream:
      bindings:
        paymentCompleted-in-0:
          destination: payment-events
          group: shipping-service-group


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
